name: Harvest PyPI stats
on: push

jobs:
  harvest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: pypi-stats
    - name: Harvest daily downloads information
      run: |
        mkdir kestrel-lang
        cd kestrel-lang
        pip install -U pip
        pip install pypistats
        filename=$(date +"%m-%d-%y-%H-%M-%S").json
        pypistats overall -f json -d kestrel-lang > $filename
        git add $filename
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "check and add daily download information"
        git push
